version: '3'
services:
  server1:
    image: nginx:latest
    ports:
      - "8081:80"
    - "5000:5000"  # Broadcasting to server2 and server3

  server2:
    image: nginx:latest
    ports:
      - "8082:80"
    - "5000:5000"  # Broadcasting from server1

  server3:
    image: nginx:latest
    ports:
      - "8083:80"
    - "5000:5000"  # Broadcasting from server1

  server4:
    image: nginx:latest
    ports:
      - "8084:80"
    - "5001:5001"  # Multicast from server4 to server5

  server5:
    image: nginx:latest
    ports:
      - "8085:80"
    - "5001:5001"  # Multicast to server5

networks:
  mynetwork:
    driver: bridge
