version: '3'
services:
  server1:
    image: broadcast-sender-image 
    container_name: broadcast-sender
    ports:
      - "8081:80"
    networks:
      - mynetwork

  server2:
    image: broadcast-receiver-image
    container_name: broadcast-receiver
    ports:
      - "8082:80"
    networks:
      - mynetwork

  server3:
    image: multicast-sender-image
    container_name: multicast-sender
    ports:
      - "8083:80"
    networks:
      - mynetwork

  server4:
    image: multicast-receiver-image
    container_name: multicast-receiver1
    ports:
      - "8084:80"
      - "5000:5000"
    networks:
      - mynetwork

  server5:
    image: multicast-receiver-image
    container_name: multicast-receiver2
    ports:
      - "8085:80"
      - "5001:5000"  
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
