
# Server configuration (Modify as needed)
HOST = localhost
PORT = 8080

server:
	python3 server.py

broadcast:
	python3 broadcast_publisher.py
	python3 broadcast_subscriber.py

multicast:
	python3 multicast_sender.py
	python3 multicast_receiver.py
